baseURL = "https://drenge.dk/"
languageCode = "da"
title = "Drenge"

disableKinds = ["taxonomy", "term"]

[params]
  description = "Vi gør det du ikke gider."
  phone = "+45 12 34 56 78"
  email = "drengefyn@gmail.com"
